# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bb11fb9e688fe32b922fe7991c6cb2e74e3858acfa7ee4dd94e6552c1996b42b947fbc1cb0fc8416cb4aa106c5d5b6d3c17394fa149bf1554e431072bc5c588

test:
  secret_key_base: 55f66c32ae8b0246c30f6e5874286632b47652d33e92e53ff35d7723d7e2bbec36eedc39973fea6e69d374613a3ed1602e89dfa730a3a704ab09adf3f1a458dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
